#!/bin/sh

base=/var/www/html/svg
domain=lab10.after8.fi

case "$1" in
    hourly)
        hour="$(date '+%_H')"
        xlabel="$(($hour))-$(($hour+1))+o%27clock+on+$(date '+%Y-%m-%d')"
        filename="hourly/$(date '+%Y-%m/%d/%H')"
        directories="hourly/$(date '+%Y-%m') hourly/$(date '+%Y-%m/%d')"
        timespan=1h
        avg=1
        divisions=4
        width=480
    ;;
    daily)
        xlabel="$(date '+The+day+of+%Y-%m-%d')"
        filename="daily/$(date '+%Y-%m/%d')"
        directories="daily/$(date '+%Y-%m')"
        timespan=1d
        avg=3
        divisions=24
        width=960
    ;;
    weekly)
        xlabel="$(date '+Week+%V+of+year+%Y')"
        filename="weekly/$(date '+%Y-%V')"
        directories=""
        timespan=1w
        avg=15
        divisions=7
        width=1400
    ;;
    *)
        echo "Invalid argument" >/dev/stderr
        exit 1
    ;;
esac

for directory in $directories; do
    if ! [ -d $base/$directory ]; then
        mkdir $base/$directory
    fi
done

for parameter in temperature windspeed wind-direction; do
    case $parameter in
        temperature)
            key=t
            round=1
            height=400
            ylabel="Temperature: %c2%b0C"
            # The temperature graph is full of unnatural jitter.
            min_avg=3
        ;;
        windspeed)
            key=w
            round=5
            height=400
            ylabel="Wind: m/s"
            min_avg=1
        ;;
        wind-direction)
            key=w-d
            round=45
            height=600
            ylabel="Wind heading: %c2%b0"
            min_avg=1
        ;;
        *)
            echo "BUG" >/dev/stderr
            exit 1
        ;;
    esac
    old_avg=$avg
    if [ $avg -lt $min_avg ]; then
        avg=$min_avg
    fi
    URL="http://$domain/graph.cgi?number-size=12&label-size=20"
    for url_parameter in key timespan avg round divisions width height xlabel ylabel; do
        URL="${URL}&${url_parameter}=$(eval echo '$'$url_parameter)"
    done
    wget -O "$base/${filename}.${parameter}.svg" "$URL"
    avg=$old_avg
done
