#!/bin/sh

n=132

cat >index.html <<END
<!DOCTYPE html>
<html leng="en" xmlns="http://www.w3.org/1999/xhtml">
    <head>
        <meta charset="utf-8"/>
        <meta name="viewport" content="width=device-width, initial-scale=1"/>
        <title>Weather station, Pictures</title>
    </head>
    <body>
        <p><a href="..">Parent directory</a></p>
        <p>
END

cat >sitemap.xml <<END
<?xml version="1.0" encoding="UTF-8"?>
<urlset
    xmlns="http://www.sitemaps.org/schemas/sitemap/0.9"
    xmlns:i="http://www.google.com/schemas/sitemap-image/1.1"
    xmlns:v="http://www.google.com/schemas/sitemap-video/1.1"
>
    <url>
        <loc>http://lab10.after8.fi/stuff/pictures/</loc>
END

for i in $(seq -w 1 $n); do
    echo "<a href='$(echo $i.*)'><img src='thumbnails/$i.jpeg' " >>index.html
    if [ -e alt/$i ]; then
        echo "alt='$(cat alt/$i)' title='$(cat alt/$i)' " >>index.html
        if [ -n "$(echo $i.* | grep -E 'mp4|ogv')" ]; then
            echo "<v:video>" >>sitemap.xml
            echo "<v:thumbnail_loc>http://lab10.after8.fi/stuff/thumbnail/$i.jpeg</v:thumbnail_loc>" >>sitemap.xml
            echo "<v:title>$(cat alt/$i)</v:title>" >>sitemap.xml
            echo "<v:description>$(cat alt/$i)</v:description>" >>sitemap.xml
            echo "<v:content_loc>http://lab10.after8.fi/stuff/$(echo $i.*)</v:content_loc>" >>sitemap.xml
            echo "</v:video>" >>sitemap.xml
        else
            echo "<i:image>" >>sitemap.xml
            echo "<i:loc>http://lab10.after8.fi/stuff/pictures/$(echo $i.*)</i:loc>" >>sitemap.xml
            echo "<i:title>$(cat alt/$i)</i:title>" >>sitemap.xml
            echo "<i:caption>$(cat alt/$i)</i:caption>" >>sitemap.xml
            #echo "<i:license>???</i:license>" >>sitemap.xml
            echo "</i:image>" >>sitemap.xml
        fi
    else
        echo "alt='' title='$i' " >>index.html
    fi
    echo "width='96' height='96'/></a>" >>index.html
done

cat >>index.html <<END
        </p>
        <p>
END

for i in $(seq -w 1 $n); do
    if [ -e alt/$i ]; then
        echo "<a href='$(echo $i.*)'>$(cat alt/$i)</a><br/>" >>index.html
    else
        echo "<a href='$(echo $i.*)'>$i</a><br/>" >>index.html
    fi
done

cat >>index.html <<END
        </p>
    </body>
</html>
END

echo "</url></urlset>" >>sitemap.xml
