#!/bin/sh

n=132

cat >index.html <<END
<!DOCTYPE html>
<html leng="en" xmlns="http://www.w3.org/1999/xhtml">
    <head>
        <meta charset="utf-8"/>
        <meta name="viewport" content="width=device-width, initial-scale=1"/>
        <title>Weather station, Pictures</title>
    </head>
    <body>
        <p><a href="..">Parent directory</a></p>
        <p>
END

for i in $(seq -w 1 $n); do
    echo "<a href='$(echo $i.*)'><img src='thumbnails/$i.jpeg' " >>index.html
    if [ -e alt/$i ]; then
        echo "alt='$(cat alt/$i)' title='$(cat alt/$i)' " >>index.html
    else
        echo "alt='' title='$i' " >>index.html
    fi
    echo "width='96' height='96'/></a>" >>index.html
done

cat >>index.html <<END
        </p>
        <p>
END

for i in $(seq -w 1 $n); do
    if [ -e alt/$i ]; then
        echo "<a href='$(echo $i.*)'>$(cat alt/$i)</a><br/>" >>index.html
    else
        echo "<a href='$(echo $i.*)'>$i</a><br/>" >>index.html
    fi
done

cat >>index.html <<END
        </p>
    </body>
</html>
END

